import tkinter as tk
import estilos as css
app = css.interfaz()
entradas = css.cuadro(app)
entradas.grid(column = 0, row = 0)
titulo1 = tk.Label(entradas,text = "Dato 1")
titulo1.grid(column = 0, row = 0)
entrada1 = tk.Entry(entradas)
entrada1.grid(column = 0, row = 1)
titulo2 = tk.Label(entradas,text = "Dato 2")
titulo2.grid(column = 0, row = 2)
entrada2 = tk.Entry(entradas)
entrada2.grid(column = 0, row = 3)
titulo2 = tk.Label(entradas,text = "Dato 3")
titulo2.grid(column = 0, row = 4)
entrada2 = tk.Entry(entradas)
entrada2.grid(column = 0, row = 5)
entrada3 = tk.Entry(app)
entrada3.grid(column = 1, row = 0)
app.mainloop()
